---
benchmark_config:
  generic:
    benchmark: redis
    cpus: 0
    skip_clear_page_cache: false
    transparent_hugepages: always
    overcommit_memory: never_check
  redis:
    record_count: 100000
    operation_count: 100000
    read_proportion: 0.20
    update_proportion: 0.10
    insert_proportion: 0.10
    rmw_proportion: 0.10
    scan_proportion: 0.10
    delete_proportion: 0.30
    request_distribution: "zipfian"
collector_config:
  generic:
    poll_rate: 0.1
    output_dir: data
    output_graphs: false
    hooks:
      - mm_rss_stat
      - process_trace
      - madvise
      - perf
      - unmap_range
